### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by phreak1979** [e7d/speedtest#4]
Hi, the command line arguments don't work node server.js 80 ../web/dist . I changed it in the server.js file and its working great. 
My actual question is there a way to get a report of who has tested and what the values are? Is there a database?

Thanks
Phreak

**Comment by e7d** [comment]
Hi phreak.
Sorry for the late response. The results are not really meant to be consulted by the administrators. However, you can find the shareable image of each speed test result in the "results" folder.
