### ISSUE TITLE
Cannot start speedtest on Safari 13.0.3

### ISSUE THREAD

**Issue by dwinurhadia** [e7d/speedtest#6]
Dear Sir, 
I have error to start speedtest when i used safari, and having error **TypeError: Reflect.construct requires the first argument be a constructor**    on line `} : r.exports = o = Reflect.construct, o.apply(null, arguments)`

Preview screenshoot here
https://prnt.sc/q8osca
https://prnt.sc/q8osp2

**Comment by e7d** [comment]
Hi,
Thank you for this. I'll give it a look as soon as I can get a Mac to test it.

**Comment by markcarver** [comment]
Same thing on all iOS devices (since it uses Safari for any webkit view)

**Comment by voidpls** [comment]
Yup, latest Safari on iOS is broken

**Comment by e7d** [comment]
Hello @dwinurhadia, @markcarver and @voidpls.

There was actually a bug regarding Safari XHR events handling.
Could you test if the current develop version is working for you?
http://134.209.196.181:8081/

Be sure to clear your cache before testing.

Thanks and regards.

**Comment by markcarver** [comment]
@e7d I just tested in safari on my mac, it works 😃

**Comment by voidpls** [comment]
Yup, works on latest iOS

**Comment by dwinurhadia** [comment]
Yes, It's works.
Thank you 😄

**Comment by markcarver** [comment]
bump

**Comment by e7d** [comment]
@markcarver I published a new [0.5.1](https://github.com/e7d/speedtest/releases/tag/v0.5.1) release yesterday. Please ho ahead and try it.

**Comment by markcarver** [comment]
Perfect, thank you :D
